name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install, build, and test
        run: |
          yarn
          yarn lint
          yarn build
        env:
          CI: true
      - name: Auto publish to NPM
        if: matrix.node-version == '12.x'
        uses: luvies/action-yarn-publish@master
        with:
          skipped-versions: 0.0.4 || 0.0.6
          git-tag: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Switch to github registry
        if: matrix.node-version == '12.x'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Auto publish to github
        if: matrix.node-version == '12.x'
        uses: luvies/action-yarn-publish@master
        with:
          skipped-versions: 0.0.4 || 0.0.6
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
